### PR TITLE
Added reactive event handler

### PR DESCRIPTION
**Pull request by etschelp**

### CODE REVIEW

**Comment by etschelp** [comment]
@tdiesler I have been thinking a lot about how to make testing easier, especially when working with websockets where there are multiple threads that need to be synchronised. So I had the idea to introduce reactive streams as a solution. In the connect two subwallets test you see how this could look like: https://github.com/hyperledger-labs/acapy-java-client/blob/1ccdf6ddc1d7af9022d9db529ff3179d4714e45a/src/test/java/org/hyperledger/aries/api/multitenant/MultiTenantTest.java#L130

In short it is like:

```java
// create base client
// create two sub wallets
// create clients for sub wallets

// create websocket and reactive listener for sub wallet 2
ReactiveEventHandler rx = ReactiveEventHandler.builder().walletId(wallet2.getWalletId()).build();
AriesWebSocketClient socket = AriesWebSocketClient.builder()
        .apiKey(adminApiKey)
        .url("ws://localhost:" + ariesContainer.getMappedPort(IntegrationTestBase.ARIES_ADMIN_PORT) + "/ws")
        .bearerToken(wallet2.getToken())
        .handler(rx)
        .handler(new TenantAwareEventHandler.DefaultTenantAwareEventHandler())
        .build();

// wallets are prepared
// wallet 2 creates invitation
// wallet 2 receives invitation

// now wallet 2 can do this 
rx.connection().filter(ConnectionRecord::stateIsRequest).subscribe(s -> {
    try {
        sub2.connectionsAcceptRequest(s.getConnectionId(), null);
    } catch (IOException e) {
        Assertions.fail("expecting to connect", e);
    }
 });

ConnectionRecord active = rx.connection()
                .filter(ConnectionRecord::stateIsActive)
                .blockFirst(Duration.ofSeconds(5));
Assertions.assertNotNull(active);
Assertions.assertEquals(cr1.getInvitationKey(), active.getInvitationKey());
```

As the try/catch in the subscriber is not very nice I'm thinking about wrapping the checked exception into a RuntimeException.

Any feedback is welcome.

**Comment by tdiesler** [comment]
Yes, we seem to be needing yet another plugin mechanism to the WS event processing chain. The (WS) Listener delegates to the EventHandler, which sees typed representations of the messages. The Listener is scoped on the (multitenant) wallet (when we have the "default" message distribution type). Now, not every wallet wants to see the messages from all (other) wallets nor all emitted message types. We seem to be needing a plugin to the EventHandler that can filter messages by source and/or type.

The reactive API could be used for such a plugin, but might be an engineering overkill for such a (simple) plugin. I believe WS message delivery is already decoupled sufficiently such that we don't need yet another async message processing route to the message consumer. Still, the reactive API defines concepts that are well suited to talk about what is needed here. We have ...

* **Publisher** - publishes messages to interested parties (possibly async)
* **Subscriber** - subscribes to messages from a given Publisher
* **Subscription** - handles lifecycle of the Subscriber and message delivery semantics

From what I can see so far, I'd have these requirements on the message filtering system ...

1) Allow Subscriptions when the EventHandler is created (so we don't miss messages)
2) Allow dynamic subscriptions to be added/removed from a given EventHandler
3) Filter on 0:N source wallet ids - Settings does not have a source wallet - option to listen to all source wallets
4) Filter on 0:N message types -  option to listen to all message types
5) Simple message Consumer API that gives access to all aspects of the WS message and can throw checked Exceptions

To help me understand what is needed for the getting started walkthrough (so far) I also prototyped an EventHandler plugin mechanism based on the JDK Reactive API (no extra dependencies). This is mostly throw-away code for you to look at. In the end, I of course prefer this API to live in this project.

Still, here you have ...

1) An example [registering subscriptions](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/MultitenantConnectionTest.java#L61) at EventHandler build time
2) [Dynamic subscriptions](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/GettingStartedAriesTest.java#L556) on an existing EventHandler
3) Filter on [multiple wallet ids](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/MultitenantConnectionTest.java#L101)
4) Filter on [multiple message types](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/MultitenantConnectionTest.java#L101)
5) Consumer that [creates its AriesClient through the Event](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/MultitenantConnectionTest.java#L82) and makes the call without exception handling

In case, you already have the above (more or less) I'm happy to try out that API and give specific feedback before the merge if you like.

**Comment by tdiesler** [comment]
A simplified approach might be to add filtering to the EventHandler directly and hence requiring WS connections to be short lived and purpose build. In that case the reactive API might not be needed at all. WDYT?

**Comment by etschelp** [comment]
Ok many points here. First a general remark. If you look on how aca-py deals with webhooks vs.  websockets we need to make sure that we are not working around a bug here by putting too much logic into the websocket handler. To make this clearer.

If you are dealing with webhooks in multi-tenant mode aca-py allows to set a wallet dispatch type per sub-wallet and allows you to register webhook handlers on a sub-wallet basis. Like this, events are already separated on the aca-py side, and a sub-wallet handler never sees events from another wallet. The base wallet being the exception here.

If you compare this with what is happening with webhooks my guess is that there are simply some implementation details missing in aca-py, because I would expect that if I connect a websocket with a Bearer token that all events are already filtered by the sub-wallets token. Everything else is a potential security risk. Imagine someone is hosting a multi-tenant enabled aca-py to companies A and B, and B sees all events of A. Long story short I would expect that the websocket client behaves in the same way as the rest client meaning that you need to create a new instance for each sub wallet.

Concerning the other points.

In my understanding the websocket client is the publisher and the handler is the subscriber. In the PR I switched to a handler list so that you can push as many handlers as needed.
```java
AriesWebSocketClient socket = AriesWebSocketClient.builder()
        .handler(h1)
        .handler(h2)
        .build();
```
I have not thought about making this dynamic, because my use cases are static atm, also usually I simply throw away and recreate, but changing this is not a problem.

Filtering by sub wallet happens in the handler:
```java
ReactiveEventHandler h1 = ReactiveEventHandler.builder().walletId(wallet2.getWalletId()).build();
```
Meaning one handler per sub wallet, but this can also be extended to a list of ids. But as mentioned above this should not be needed at all imho.

I believe so far this is pretty close to what you are doing, what is different is that my reactive implementation is already pre filtered and one can subscribe for example to a stream of connection events and then filter by event attributes like:
```java
h1.connection().filter(ConnectionRecord::stateIsRequest).subscribe(System.out::println)
```
The subscribe part can take any consumer. 

The main reason for introducing the reactor framework was that this allows for easier thread synchronisation and hence easier testing, because in the raw implementation you either have to manually synch the threads or do all the testing in the consumer. Whereas with reactor you can block and wait and hence synch within the test thread like:

```java
ConnectionRecord active = h1.connection()
                .filter(ConnectionRecord::stateIsActive)
                .blockFirst(Duration.ofSeconds(5));
Assertions.assertEquals("1234", active.getInvitationKey());
```

Ok where to go from here? As both ways have its merits I think a compromise would be that the websocket clients accepts the following:
-  the handler interface which is more coarse granular 
- a tuple of event class and consumer
- 0:N wallet ids
```java
AriesWebSocketClient socket = AriesWebSocketClient.builder()
        .walletId("1")
        .walletId("2")
        .handler(h1)
        .subscribe(ConnectionRecord.class, System.out::println)
        .build();
```
Then it is up to the user of the api what implementation to choose. The only thing that I would not do is add more filter options to the websocket client. Also what is totally in the responsibility of the client is the decision to block in the handler/subscriber here you can shoot yourself in the foot pretty quickly. The reactor framework is more lenient here as it allows back pressure in this case.

**Comment by tdiesler** [comment]
This looks very good ...

* I also believe we are looking at an aca-py bug or at least at a not very well defined area of event visibility
* Not having dynamic WS listeners should work fine for now
* "easier thread synchronisation" - yes, I didn't think of that - I have [latches all over](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/GettingStartedTest.java#L618)

> add more filter options to the websocket client

We don't do that, right? AFAIK, a WS client [registers a listener which then delegates to a handler](https://github.com/tdiesler/nessus-aries/blob/main/common/src/main/java/io/nessus/aries/common/websocket/WebSockets.java#L22)

Regarding event visibility, I have this [awkward code here](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/GettingStartedTest.java#L476). As you can see, the Inviter listens to events from the Invitee and vice versa. It may only work because of that presumed visibility bug.

Finally, what about throwing checked exceptions from the consumer? Would [this](https://github.com/tdiesler/nessus-aries/blob/main/common/src/main/java/io/nessus/aries/common/SafeConsumer.java) be an option?

> where to go from here?

I suggest you give me a shout when you're done with your branch. Then, I migrate my code over and after going back and forth a few times we merge to main. You can always meet me in Discord for a quick chat.

**Comment by tdiesler** [comment]
I revisited the [connection code](https://github.com/tdiesler/nessus-aries/blob/main/common/src/main/java/io/nessus/aries/wallet/ConnectionHelper.java#L46) and as it turns out here to we can filter on the wallet that owns the ws connection. In fact, I could remove the filter by wallet API completely, [except for the revoke notify case](https://github.com/tdiesler/nessus-aries/blob/main/itests/smoke/src/test/java/io/nessus/aries/test/GettingStartedTest.java#L1219) when Alice wants to see the revoked CredentialExchange - this event is published by Acme.

**Comment by etschelp** [comment]
I played around with this some more, the fine granular handlers are a bit of a pain as Java does not work very well with dynamic types, but in the end it should not really matter because I directly made the client a handler so now it is like:

```java
AriesWebSocketClient ws = AriesWebSocketClient.builder()
        .apiKey("123")
        .walletId("1") // optional 0:N
        .walletId("2")
        .handler(new TenantAwareEventHandler.DefaultTenantAwareEventHandler()) // optional 0:N
        .build();
```
And all events are directly accessible:
```java
ConnectionRecord active = ws.connection()
                .filter(ConnectionRecord::stateIsActive)
                .blockFirst(Duration.ofSeconds(5));
```
If you like you can take this for a first test drive.

**Comment by tdiesler** [comment]
Ok, thanks - will do. It might take a little while however ...

**Comment by tdiesler** [comment]
We could say, if a clients opens a WS it is also responsible for consuming all events and when done, close the WS. Alternatively, a WS connection could (lazily) be [associated with the wallet ](https://github.com/tdiesler/nessus-aries/blob/reactive-streams/common/src/main/java/io/nessus/aries/wallet/NessusWallet.java#L61) and the client opens/closes subscriptions on individual event types. Events that the client is not interested in, would be ignored and would hence not fill buffers/sinks

**Comment by etschelp** [comment]
The nice thing here is that multicast sinks do not start producing any events as long as there aren't any subscribers, so events are gone/ignored if no one is there to listen. This is different for replay or unicast sinks where one would receive previous events depending on the buffer size: https://projectreactor.io/docs/core/release/reference/#sinks The subscriber is created together with the flux when calling `ws.connection()` for example, not before. 

One possible issue is if there is a slow subscriber and events are coming in faster than they are taken from the buffer then the backpressure buffer would fill up and events would get lost. And theoretically if there are many slow subscribers and many events with huge payloads memory could indeed file up. But I see this in the responsibility of the clients to handle this correctly, same as calling dispose() on the flux if needed.

But I think it makes sense to make the WebSocketClient implement AutoClosable, like this most IDE's will even warn you if the client is not closed.

**Comment by tdiesler** [comment]
Ok, all good then. How about we build the WS client functionality into the WalletRecord or a higher level Wallet thing that can be obtained from the Wallet builder - similar to what I have in NessusWallet? Note, how this is [awkwardly constructed](https://github.com/tdiesler/nessus-aries/blob/main/common/src/main/java/io/nessus/aries/wallet/NessusWallet.java#L32) with a json roundtrip.

**Comment by tdiesler** [comment]
> I would preferably do this in a new branch, and merge this one first.

Ok, let's do that. Are you blocked by 0.7.4 for this merge?

**Pull request merged**
