### PR TITLE
[#24] Cannot handle non-payload WebSocket events

### PR DESCRIPTION
**Pull request by tdiesler**
Signed-off-by: Thomas Diesler <tdiesler@redhat.com>

### CODE REVIEW

**Comment by tdiesler** [comment]
This has now been rebased on your stuff

**Comment by etschelp** [comment]
OK, lets compromise, please have a look at: https://github.com/hyperledger-labs/acapy-java-client/pull/32

There I added the exception handling to the tenant aware handler, as this is new code I do not care so much about changing behaviour. For the existing EventHandler I need some more time to play around and think this through as it somewhat breaks the existing contract. 

Also the contract in the existing code is that the handler implementation never receives null, I therefore changed your code so that this never happens because `null` becomes `"{}"`, so instead of null an empty object is pushed. So your changes here shouldn't be needed.

I hope this works for you.

**Comment by etschelp** [comment]
I figured out where this is coming from. This is a conflict between aca-py's Ping message and a websocket ping message that is used to keep the socket open see: https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2 They should be ignored, adjusting the handlers here is not needed. I adjusted the socket handler in the other PR accordingly.

**Comment by tdiesler** [comment]
ok, good to know

**Pull request closed without merging**
