### PR TITLE
WebSocket/Webhook processing swallows (optional) wallet_id

### PR DESCRIPTION
**Pull request by tdiesler**
There are some breaking changes in EventHandler - I tried to minimize this by deprecation callback methods without wallet id. Not sure if you want that - perhaps it is ok to change those signatures

### CODE REVIEW

**Comment by etschelp** [comment]
No I definitely do not want that. I'm aware of that issue and I'm currently working on that, there will be another class called TanentAwareEventHandler that takes care of that

**Comment by tdiesler** [comment]
Those breaking changes would affect folks who override

```
public void handleEvent(String topic, String payload)
public void handleRaw(String topic, String payload)
```

**Comment by etschelp** [comment]
See this one: https://github.com/hyperledger-labs/acapy-java-client/pull/30

Like this you can choose what to implement. Existing clients with basic wallets can keep using the existing implementation, new multi tenant clients can use the tenant aware handler. As both implementations are an option there is no need to deprecate the existing one.

In the websocket handler you can switch from EventHandler to IEventHandler and can either switch the methods depending on the existence of the walletId or always use the method with the walletId parameter.

**Comment by tdiesler** [comment]
Ok, looks good. The one thing I'd really like to preserve is the exception handling in the EventHandler

Callback signatures like this make sense IMHO, because it allows clients to throw stuff which is then handled by the EventHandler, instead of in each callback method implementation. `log.error("Error in webhook event handler:", e)` should be reachable for exceptions from these callbacks. 

```
public void handleConnection(String walletId, ConnectionRecord connection) throws Exception 
```

My suggested approach is [here](https://github.com/tdiesler/acapy-java-client/blob/feature/tenant-aware-event-handler/src/main/java/org/hyperledger/aries/webhook/TenantAwareEventHandler.java#L87)

I also [rebased #28](https://github.com/tdiesler/acapy-java-client/commit/1e7c20c877b2b50b318ceb50f1bbb265b6d731ce) on top of your stuff. I can do this properly again when TenantAwareEventHandler reaches the main branch

The test case that requires both (i.e. exceptions from handler callbacks and settings support) is [here](https://github.com/tdiesler/nessus-aries/blob/next/itests/smoke/src/test/java/io/nessus/aries/test/MultitenantConnectionTest.java#L65) - borrow freely.

**Comment by tdiesler** [comment]
Here, Faber [receives a connection invitation in a event handler](https://github.com/tdiesler/nessus-aries/blob/next/itests/smoke/src/test/java/io/nessus/aries/test/MultitenantConnectionTest.java#L87), which is declared to throw an IOException. I'd think this is a common enough use case (i.a. call AriesClient from a handler). Would it not be better to allow that? A client prepared to handle checked exceptions in a meaningful can still do it or alternatively let the base class handle it with an error msg.

**Comment by tdiesler** [comment]
out-of-date

**Pull request closed without merging**
